### ISSUE TITLE
Possivel solução para o problema das imagens

### ISSUE THREAD

**Issue by AndersonFirmino** [joaovitor11/EstudoCppp#1]
A solução seria colocar o nome do arquivo sem espaços. 
Tenta usar underline ou traços 
- ou _ 

Acho que isso vai resolver o problema 

:coffee: :laughing:

**Comment by joaovitor11** [comment]
Consegui depois de muitas tentativas, basta você deixa a pasta das imagens na mesma pasta que o ReadMe.md, assim você chama apenas o caminho img/nome_imagem.png.

Valeu pelo apoio até aqui, man! Tô curtindo pra caramba kkkkkkk

**Comment by AndersonFirmino** [comment]
Isso ai man. Agora fecha a issue man. :laughing:
